import { describe, it } from 'node:test';
import assert from 'node:assert';
import crypto from 'crypto';
import {
    generateOtpCode,
    generateSalt,
    hashOtp,
    tokenLookupHash,
    timingSafeStringCompare,
    generateInvertedToken,
    verifyAdminKey
} from '../src/services/cryptoService.js';
import { config } from '../src/config.js';

describe('Crypto Compatibility Contract (Gateway vs Bot Main Engine)', () => {
    it('generates 6-digit zero-padded OTP codes', () => {
        for (let i = 0; i < 20; i++) {
            const code = generateOtpCode();
            assert.strictEqual(code.length, 6);
            assert.match(code, /^\d{6}$/);
        }
    });

    it('generates 32-byte (64 hex characters) salts', () => {
        const salt = generateSalt();
        assert.strictEqual(salt.length, 64);
        assert.match(salt, /^[0-9a-f]{64}$/);
    });

    it('computes HMAC-SHA256 OTP hashes matching main bot logic', () => {
        const code = '123456';
        const salt = 'a'.repeat(64);
        const secret = config.OTP_SECRET;

        const expected = crypto.createHmac('sha256', secret).update(`${salt}:${code}`).digest('hex');
        const computed = hashOtp(code, salt);

        assert.strictEqual(computed, expected);
    });

    it('computes server-peppered deterministic lookupHash matching main bot logic', () => {
        const token = 'cosmos-abc123-7890';
        const secret = config.OTP_SECRET;

        const expected = crypto.createHmac('sha256', secret).update(token.trim().toUpperCase()).digest('hex');
        const computed = tokenLookupHash(token);

        assert.strictEqual(computed, expected);
        // Case-insensitivity verification
        assert.strictEqual(tokenLookupHash('COSMOS-ABC123-7890'), tokenLookupHash('cosmos-abc123-7890'));
    });

    it('performs timing-safe string comparison without length or timing leaks', () => {
        assert.strictEqual(timingSafeStringCompare('secret-token-123', 'secret-token-123'), true);
        assert.strictEqual(timingSafeStringCompare('secret-token-123', 'secret-token-124'), false);
        assert.strictEqual(timingSafeStringCompare('short', 'much-longer-string'), false);
    });

    it('generates inverted tokens formatted as COSMOS-XXXXXX-<last4>', () => {
        const phone = '+62 812-3456-7890';
        const token = generateInvertedToken(phone);
        assert.match(token, /^COSMOS-[0-9A-F]{6}-7890$/);
    });

    it('verifies admin key in constant time supporting optional Bearer prefix', () => {
        config.ADMIN_API_KEY = 'test-super-secret-admin-key';

        assert.strictEqual(verifyAdminKey('Bearer test-super-secret-admin-key'), true);
        assert.strictEqual(verifyAdminKey('test-super-secret-admin-key'), true);
        assert.strictEqual(verifyAdminKey('Bearer wrong-key'), false);
        assert.strictEqual(verifyAdminKey(''), false);
        assert.strictEqual(verifyAdminKey(undefined), false);
    });

    it('cross-verifies: OTP generated by gateway validates with main hash formula', () => {
        const code = generateOtpCode();
        const salt = generateSalt();
        const codeHash = hashOtp(code, salt);

        // Verification formula on bot side
        const botExpected = crypto.createHmac('sha256', config.OTP_SECRET).update(`${salt}:${code}`).digest('hex');
        assert.strictEqual(codeHash, botExpected);
    });
});
